export const metricStrings = {
  salesRevenue: "Sales Revenue",
  costOfRevenue: "Cost of Revenue / Cost of Sales",
  grossProfit: "Gross Profit",
  operatingExpenses: "Operating Expenses",
  operatingIncome: "Operating Income",
  interestExpenses: "Interest Expense (Finance Costs)",
  incomeTaxes: "Income Taxes (Tax Expenses)",
  netIncome: "Net Income",
  earningsPerShare: "Earnings per Share (EPS)",
  pERatio: "P/E Ratio",
  earningsYield: "Earnings Yield",
  gpmRatio: "Gross Profit Margin Ratio",
  opmRatio: "Operating Profit Margin Ratio",
  npmRatio: "Net Profit Margin Ratio",
  ebit: "EBIT (Earnings/Income Before Income Tax",
  otherIncome: "Other Income",
  totalAssets: "Total Assets",
  totalLiabilities: "Total Liabilities",
  rOEquity: "Return on Equity (RoE)",
  currentAssets: "Current Assets",
  currentLiabilities: "Current Liabilities",
  shortTermDebts: "Short Term Debts",
  longTermDebts: "Long Term Debts",
  currentRatio: "Current Ratio",
  interestCoverageRatio: "Interest Coverage Ratio",
  workingCapitalDebtRatio: "Working Capital to Debt Ratio",
  operatingCashflow: "Cashflow from Operating Activities",
  investingCashflow: "Cashflow from Investing Activities",
  financingCashflow: "Cashflow from Financing Activities",
  capEx: "Capital Expenditures",
  freeCashflow: "Free Cashflow",
  cashflowGtLongTermDebt: "3x Cashflow > Long Term Debt?",
  dividendYield: "Dividend Yield",
  totalDivs: "Total Dividends in a year",
  divPayoutRatio: "Dividend Payout Ratio",
};
